version: '3.4'

services:
  trythatbackend:
    image: trythat_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: trythat_backend
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://localhost:27017
    volumes:
      - ./:/app
      - /app/node_modules

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
